### ISSUE TITLE
When Prereq errors, the message is not great

### ISSUE THREAD

**Issue by raybooysen** [esp/esp-js-ui#43]
When a pre-req errors, the pre-req loader sends an error message in the form `Error Loading ${preReqName}`.

However, pre-req names are in the form "Loading Ref Data", "Opening Connection".  So the resultant names of "Error Loading Loading Ref Data" and "Error Loading Opening Connection" don't read well.

**Comment by raybooysen** [comment]
https://github.com/esp/esp-js-ui/blob/master/src/ui/modules/singleModuleLoader.ts#L124

**Comment by KeithWoods** [comment]
This issue was moved to esp/esp-js#185
