### ISSUE TITLE
ModuleBase should include the ability for a Module to load Async data

### ISSUE THREAD

**Issue by raybooysen** [esp/esp-js-ui#5]
A common requirement is for a module to load some async data before it is ready to go.  ModuleBase currently only supports syncronous functions as it's lifecycle.  There should be an additional function to allow modules to tell the ModuleLoader when it is ready.

Additionally this should be more than just a Promise or an Observable that yields a single item.  A better model would support a loading screen where we see something similar to:

```
Started loading Foo
Foo finished
Started loading Bar
```  

This lets us power a loading screen where we can inform the user.

For error cases, I think the best cases is that if this Observable errors, the module loaders stops loading the module completed.  Trying to handle error cases where a module has partially loaded it's async data is almost an impossible task.

**Comment by KeithWoods** [comment]
Sounds sensible. 

There is a case here for modules to have separate workflow to load. i.e. module B shouldn't wait for module C it should just load when it's done. However they both might require module A to be done.

First cut is just get something in, then we can add such bells and whistles later (unless this is a case for vNext?).

**Comment by raybooysen** [comment]
Fixed in #20 as a first cut.
