### ISSUE TITLE
ModuleLoader loadModules Generic Type

### ISSUE THREAD

**Issue by raybooysen** [esp/esp-js-ui#9]
`loadModules` on `ModuleLoader` looks like this:

```
    loadModules<TModule extends ModuleConstructor>(...functionalModules: Array<TModule>): void;
```

Shouldn't this be:
```
loadModules<ModuleBase>(...functionalModules: Array<ModuleBase>): void;
```

Since the module loader should expects `ModuleBase` instances because of the lifecycle functions, this will make it simpler to consume.

**Comment by raybooysen** [comment]
Ah I see why this exists, you're passing in the ctor function, so it can be created...

**Comment by KeithWoods** [comment]
Yes it's so the child container can be injected into the module:

```
export interface ModuleConstructor {
    new (container: Container, stateService: StateService): Module;
}
```

Not sure you'd ever want something else to create the modules. Perhaps?. Ideally this, and other parts of the framework could be hidden behind something more abstract, perhaps a fluent api to configure things.

**Comment by KeithWoods** [comment]
This issue was moved to esp/esp-js#190
